version: "3"

# pihole wants ip of dns resolver, not hostname of stubby, i had to define static ip to them.
networks:
    pihole:
      ipam:
        config:
          - subnet: 172.20.0.0/24

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
#sudo systemctl disable systemd-resolved.service
#sudo systemctl stop systemd-resolved
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:beta-v5.0  # pihole/pihole:latest for latest non beta version.
    networks:
        pihole:
            ipv4_address: 172.20.0.5
    ports:
      - "53:53/tcp"  # you must disable and stop systemd-resolved first, otherwise it can't bind this port. 
      - "53:53/udp"
      - "67:67/udp"
      - "8880:80/tcp"  # i'll use a nginx reverse proxy for my container
      - "8443:443/tcp" # so i need 80/443 port for something else.
    environment:
      TZ: 'Europe/Istanbul'  # replace with your time zone
      # WEBPASSWORD: 'set a secure password here or it will be random'
      # "docker exec -it pihole pihole -a -p"    ## then enter your password into the prompt
    # Volumes store your data between container upgrades
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
    #  - NET_ADMIN
    restart: unless-stopped

  stubby:
    container_name: stubby
    #use latest tag for linux/amd64 build, use raspberry tag for linux/arm
    image: emre1393/stubby:raspberry
    networks:
        pihole:
            ipv4_address: 172.20.0.10
    ports:
      - "5053:53/udp"
    environment:
        TZ: 'Europe/Istanbul'
    dns:
      - 127.0.0.1
    